FROM ruby:<%= @data.ruby_version %>-alpine

ENV RAILS_ENV=development
ENV EDITOR=vim
WORKDIR /app

RUN apk add --update --no-cache \
    alpine-sdk \
    nodejs \
    yarn \
    tzdata \
    gcompat \
    vim \
    <%- if @adapter =~ /mysql/ -%>
    mysql-dev
    <%- else -%>
    postgresql-dev
    <%- end -%>
RUN gem install bundler -v <%= @data.bundler_version %>

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs=2

COPY . .

EXPOSE 3000

ENTRYPOINT ["./entrypoints/docker-entrypoint.sh"]

CMD ["./bin/rails", "server"]
