FROM ruby:<%= @data.ruby_version %>-alpine

ENV RAILS_ENV=development
ENV EDITOR=vim
WORKDIR /rails

RUN apk add --update --no-cache \
    alpine-sdk \
    nodejs \
<%- if @webpack_container_needed -%>
    yarn \
<%- end -%>
    tzdata \
    gcompat \
    vim \
    bash \
    openssh \
<%- if @adapter =~ /mysql/ -%>
    mysql-dev
<%- else -%>
    postgresql-dev
<%- end -%>
RUN gem install bundler -v <%= @data.bundler_version %>

<%- if @webpack_container_needed -%>
COPY package.json yarn.lock ./
RUN yarn install
<%- end -%>

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs=2

COPY . .

RUN sed -i 's:/bin/ash:/bin/bash:g' /etc/passwd

EXPOSE 3000

ENTRYPOINT ["./bin/docker-entrypoint"]

CMD ["sleep", "infinity"]
