FROM ruby:<%= @data.ruby_version %>-alpine

ENV RAILS_ENV=development
ENV EDITOR=vim
WORKDIR /rails

RUN apk add --update --no-cache \
    alpine-sdk \
    nodejs \
    tzdata \
    gcompat \
    vim \
    bash \
    openssh \
<%- if @adapter =~ /mysql/ -%>
    mysql-dev
<%- else -%>
    postgresql-dev
<%- end -%>
RUN gem install bundler -v <%= @data.bundler_version %>

<%- case @js_engine -%>
<%- when :webpacker -%>
RUN apk add yarn

# Install node modules
COPY package.json yarn.lock ./
RUN yarn install
<%- when :bun -%>
ENV PATH=/usr/local/bun/bin:$PATH
ARG BUN_VERSION=1.0.1
RUN curl -fsSL https://bun.sh/install | bash -s -- "bun-v${BUN_VERSION}"

# Install node modules
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile
<%- end -%>

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs=2

COPY . .

RUN sed -i 's:/bin/ash:/bin/bash:g' /etc/passwd

EXPOSE 3000

ENTRYPOINT ["./bin/docker-entrypoint"]

CMD ["sleep", "infinity"]
